from typing import List, Dict

PRODUCTS: List[Dict] = [
    {
        "id": "p001",
        "name": "CopperShield 77 WP",
        "category": "fungicide",
        "description": "Professional-grade copper-based fungicide for controlling bacterial and fungal diseases. Broad spectrum protection for fruits and vegetables.",
        "price": 34.99,
        "unit": "500g",
        "rating": 4.6,
        "tags": ["bacterial_spot", "late_blight", "early_blight", "leaf_blight", "black_rot"],
        "brand": "AgroDefend",
        "in_stock": True,
    },
    {
        "id": "p002",
        "name": "Mancozeb Pro 80 WP",
        "category": "fungicide",
        "description": "Multi-site contact fungicide with excellent preventive action. Essential for resistance management programs targeting blights and leaf spots.",
        "price": 28.50,
        "unit": "1 kg",
        "rating": 4.4,
        "tags": ["early_blight", "late_blight", "septoria", "black_rot", "target_spot"],
        "brand": "PhytoGuard",
        "in_stock": True,
    },
    {
        "id": "p003",
        "name": "Azoxystrobin 23 SC",
        "category": "fungicide",
        "description": "Systemic strobilurin fungicide with curative and protectant activity. Controls a wide range of fungal diseases with long-lasting residual protection.",
        "price": 52.00,
        "unit": "250 ml",
        "rating": 4.8,
        "tags": ["early_blight", "gray_leaf_spot", "northern_leaf_blight", "target_spot", "powdery_mildew"],
        "brand": "SynthAgro",
        "in_stock": True,
    },
    {
        "id": "p004",
        "name": "Imidacloprid 200 SL",
        "category": "insecticide",
        "description": "Systemic neonicotinoid insecticide for control of sucking pests including whitefly, aphids, and leafhoppers. Ideal for virus-vector management.",
        "price": 41.75,
        "unit": "500 ml",
        "rating": 4.5,
        "tags": ["yellow_leaf_curl", "mosaic_virus", "bacterial_spot"],
        "brand": "AgroDefend",
        "in_stock": True,
    },
    {
        "id": "p005",
        "name": "Abamectin 1.8 EC",
        "category": "acaricide",
        "description": "Biological-derived acaricide/insecticide with contact and translaminar activity. Highly effective against two-spotted spider mites and leaf miners.",
        "price": 38.90,
        "unit": "500 ml",
        "rating": 4.7,
        "tags": ["spider_mites"],
        "brand": "BioControl Solutions",
        "in_stock": True,
    },
    {
        "id": "p006",
        "name": "Myclobutanil 20 EW",
        "category": "fungicide",
        "description": "Triazole systemic fungicide with both protective and curative action. Excellent for powdery mildew and scab management in fruit crops.",
        "price": 44.50,
        "unit": "250 ml",
        "rating": 4.5,
        "tags": ["powdery_mildew", "apple_scab", "cedar_rust", "black_rot"],
        "brand": "PhytoGuard",
        "in_stock": False,
    },
    {
        "id": "p007",
        "name": "Balanced NPK 12-12-17+TE",
        "category": "fertilizer",
        "description": "High-potassium compound fertilizer with trace elements, designed to enhance plant immunity and disease resistance. Ideal for fruiting vegetables and row crops.",
        "price": 22.99,
        "unit": "5 kg",
        "rating": 4.3,
        "tags": ["all_diseases", "healthy"],
        "brand": "GrowWell Nutrients",
        "in_stock": True,
    },
    {
        "id": "p008",
        "name": "Calcium-Boron Foliar Spray",
        "category": "fertilizer",
        "description": "Liquid calcium and boron micronutrient blend. Strengthens cell walls to improve resistance to bacterial and fungal penetration. Reduces tip burn and blossom end rot.",
        "price": 18.50,
        "unit": "1 L",
        "rating": 4.2,
        "tags": ["bacterial_spot", "early_blight", "all_diseases"],
        "brand": "GrowWell Nutrients",
        "in_stock": True,
    },
    {
        "id": "p009",
        "name": "Neem Oil Concentrate 3000 EC",
        "category": "biopesticide",
        "description": "Cold-pressed neem oil concentrate with naturally occurring azadirachtin. Controls soft-bodied insects, mites, and certain fungal diseases organically.",
        "price": 24.95,
        "unit": "500 ml",
        "rating": 4.1,
        "tags": ["spider_mites", "powdery_mildew", "bacterial_spot"],
        "brand": "BioControl Solutions",
        "in_stock": True,
    },
    {
        "id": "p010",
        "name": "Precision Backpack Sprayer 16L",
        "category": "equipment",
        "description": "Professional ergonomic backpack sprayer with adjustable pressure, anti-drip valve, and fan nozzle set. Ideal for efficient fungicide and pesticide application.",
        "price": 89.00,
        "unit": "1 unit",
        "rating": 4.6,
        "tags": ["all_diseases"],
        "brand": "FarmPro Equipment",
        "in_stock": True,
    },
    {
        "id": "p011",
        "name": "Pruning Shear Disinfection Kit",
        "category": "equipment",
        "description": "Complete kit with bypass pruners and concentrated disinfectant tablets for preventing disease spread during pruning operations. Essential for trunk disease management.",
        "price": 36.00,
        "unit": "1 kit",
        "rating": 4.4,
        "tags": ["black_rot", "esca", "bacterial_spot", "all_diseases"],
        "brand": "FarmPro Equipment",
        "in_stock": True,
    },
    {
        "id": "p012",
        "name": "Metalaxyl-M 4 SL",
        "category": "fungicide",
        "description": "Phenylamide systemic fungicide targeting oomycete pathogens. Fast-acting curative and protectant activity against late blight and downy mildew.",
        "price": 47.80,
        "unit": "500 ml",
        "rating": 4.7,
        "tags": ["late_blight"],
        "brand": "SynthAgro",
        "in_stock": True,
    },
    {
        "id": "p013",
        "name": "Sulfur 80 WG",
        "category": "fungicide",
        "description": "High-quality micronized sulfur wettable granule formulation. Broad-spectrum fungicide and acaricide approved for organic production systems.",
        "price": 15.99,
        "unit": "2 kg",
        "rating": 4.0,
        "tags": ["powdery_mildew", "apple_scab", "spider_mites"],
        "brand": "PhytoGuard",
        "in_stock": True,
    },
    {
        "id": "p014",
        "name": "Drip Irrigation Starter Kit",
        "category": "equipment",
        "description": "Complete drip irrigation kit for up to 50 plants. Reduces foliar wetness, minimizing bacterial and fungal disease pressure. Includes timer, emitters, and 30m tubing.",
        "price": 64.50,
        "unit": "1 kit",
        "rating": 4.8,
        "tags": ["all_diseases"],
        "brand": "IrriSmart",
        "in_stock": True,
    },
    {
        "id": "p015",
        "name": "Trichoderma Bio-Fungicide",
        "category": "biopesticide",
        "description": "Biological fungicide based on Trichoderma harzianum. Colonizes root zone to protect against soil-borne pathogens. Compatible with IPM programs.",
        "price": 29.95,
        "unit": "250 g",
        "rating": 4.3,
        "tags": ["late_blight", "early_blight", "all_diseases"],
        "brand": "BioControl Solutions",
        "in_stock": True,
    },
]

DISEASE_PRODUCT_MAP = {
    "Apple___Apple_scab": ["p003", "p006", "p013", "p010"],
    "Apple___Black_rot": ["p001", "p006", "p011", "p010"],
    "Apple___Cedar_apple_rust": ["p006", "p003", "p013", "p010"],
    "Apple___healthy": ["p007", "p008", "p014"],
    "Blueberry___healthy": ["p007", "p008"],
    "Cherry_(including_sour)___Powdery_mildew": ["p006", "p013", "p009", "p010"],
    "Cherry_(including_sour)___healthy": ["p007", "p014"],
    "Corn_(maize)___Cercospora_leaf_spot_Gray_leaf_spot": ["p003", "p002", "p010", "p007"],
    "Corn_(maize)___Common_rust_": ["p003", "p002", "p010"],
    "Corn_(maize)___Northern_Leaf_Blight": ["p003", "p002", "p007", "p010"],
    "Corn_(maize)___healthy": ["p007", "p008"],
    "Grape___Black_rot": ["p002", "p006", "p011", "p010"],
    "Grape___Esca_(Black_Measles)": ["p011", "p007", "p008"],
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": ["p001", "p003", "p010"],
    "Grape___healthy": ["p007", "p014"],
    "Orange___Haunglongbing_(Citrus_greening)": ["p004", "p007", "p008"],
    "Peach___Bacterial_spot": ["p001", "p008", "p011", "p010"],
    "Peach___healthy": ["p007", "p014"],
    "Pepper,_bell___Bacterial_spot": ["p001", "p002", "p008", "p014"],
    "Pepper,_bell___healthy": ["p007", "p014"],
    "Potato___Early_blight": ["p003", "p002", "p008", "p010"],
    "Potato___Late_blight": ["p012", "p002", "p015", "p010"],
    "Potato___healthy": ["p007", "p014"],
    "Raspberry___healthy": ["p007", "p014"],
    "Soybean___healthy": ["p007", "p008"],
    "Squash___Powdery_mildew": ["p006", "p009", "p013", "p014"],
    "Strawberry___Leaf_scorch": ["p002", "p001", "p014", "p010"],
    "Strawberry___healthy": ["p007", "p014"],
    "Tomato___Bacterial_spot": ["p001", "p002", "p008", "p014"],
    "Tomato___Early_blight": ["p003", "p002", "p008", "p010"],
    "Tomato___Late_blight": ["p012", "p002", "p015", "p010"],
    "Tomato___Leaf_Mold": ["p002", "p001", "p014", "p010"],
    "Tomato___Septoria_leaf_spot": ["p002", "p001", "p014", "p010"],
    "Tomato___Spider_mites_Two-spotted_spider_mite": ["p005", "p009", "p013", "p014"],
    "Tomato___Target_Spot": ["p003", "p002", "p010"],
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": ["p004", "p009", "p014"],
    "Tomato___Tomato_mosaic_virus": ["p007", "p008", "p011"],
    "Tomato___healthy": ["p007", "p008", "p014"],
}

CATEGORY_LABELS = {
    "fungicide": "Fungicide",
    "insecticide": "Insecticide",
    "acaricide": "Acaricide",
    "fertilizer": "Fertilizer",
    "biopesticide": "Bio-Pesticide",
    "equipment": "Equipment",
}


def get_products_for_disease(raw_class: str) -> list:
    ids = DISEASE_PRODUCT_MAP.get(raw_class, ["p007", "p010"])
    product_map = {p["id"]: p for p in PRODUCTS}
    return [product_map[pid] for pid in ids if pid in product_map]


def get_all_products() -> list:
    return PRODUCTS