RECOMMENDATIONS = {
    "Apple___Apple_scab": {
        "description": "Apple scab is a fungal disease caused by Venturia inaequalis. It produces dark, scabby lesions on leaves, fruit, and stems, significantly reducing fruit quality and marketability.",
        "causes": [
            "Fungal pathogen Venturia inaequalis",
            "Cool, wet spring weather (10–24°C with rainfall)",
            "Poor air circulation within the tree canopy",
            "Infected leaf litter from previous season",
        ],
        "treatment": [
            "Apply fungicides (captan, myclobutanil, or mancozeb) at 7–10 day intervals during wet periods",
            "Remove and destroy infected leaves and fruit promptly",
            "Prune trees to improve airflow and light penetration",
            "Apply sulfur-based sprays at green tip stage through petal fall",
        ],
        "prevention": [
            "Plant resistant apple varieties (Liberty, Freedom, Enterprise)",
            "Rake and compost or destroy fallen leaves each autumn",
            "Maintain proper tree spacing for air circulation",
            "Monitor weather forecasts and apply protective fungicides before rain events",
        ],
        "severity": "moderate",
    },
    "Apple___Black_rot": {
        "description": "Black rot is a serious fungal disease caused by Botryosphaeria obtusa, affecting apples throughout the growing season with fruit rot, leaf spot (frogeye leaf spot), and branch cankers.",
        "causes": [
            "Fungal pathogen Botryosphaeria obtusa",
            "Warm, humid conditions (24–29°C)",
            "Wounds from insects, hail, or winter injury",
            "Dead wood, mummified fruit, and bark cankers as inoculum sources",
        ],
        "treatment": [
            "Remove all mummified fruit from trees and ground",
            "Prune out dead and cankered branches, cutting 15 cm beyond visible infection",
            "Apply fungicides (captan, thiophanate-methyl) every 10–14 days",
            "Improve canopy aeration through targeted pruning",
        ],
        "prevention": [
            "Maintain tree vigor through proper fertilization and irrigation",
            "Eliminate all sources of dead wood promptly",
            "Control fire blight and other wounds that serve as entry points",
            "Apply dormant copper sprays before bud break",
        ],
        "severity": "high",
    },
    "Apple___Cedar_apple_rust": {
        "description": "Cedar-apple rust is caused by Gymnosporangium juniperi-virginianae and requires two host plants — apple and eastern red cedar — to complete its life cycle. It creates bright orange-yellow spots on apple leaves.",
        "causes": [
            "Fungal pathogen Gymnosporangium juniperi-virginianae",
            "Proximity to eastern red cedar or juniper trees (alternate host)",
            "Wet, warm spring weather during spore release",
            "Wind-dispersed basidiospores from cedar galls",
        ],
        "treatment": [
            "Apply myclobutanil or propiconazole fungicides from pink bud stage through late spring",
            "Remove cedar galls (orange, gelatinous masses) from nearby junipers before they sporulate",
            "Apply protective fungicide sprays every 7–10 days during infection periods",
        ],
        "prevention": [
            "Plant rust-resistant apple varieties (Redfree, GoldRush, Williams Pride)",
            "Remove eastern red cedar trees within 300 meters if feasible",
            "Monitor cedar trees for galls and remove before they release spores",
            "Maintain good canopy airflow through annual pruning",
        ],
        "severity": "moderate",
    },
    "Apple___healthy": {
        "description": "The plant is healthy with no visible signs of disease. Maintaining current management practices is recommended.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Continue regular monitoring for early disease detection",
            "Maintain balanced fertilization program",
            "Ensure adequate irrigation without waterlogging",
            "Practice annual pruning for optimal canopy structure",
        ],
        "severity": "none",
    },
    "Blueberry___healthy": {
        "description": "The blueberry plant is healthy. Maintain current cultural practices.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Maintain soil pH between 4.5–5.5 for optimal nutrient uptake",
            "Mulch with pine bark or wood chips to retain moisture and suppress weeds",
            "Monitor for spotted wing drosophila and mummy berry during growing season",
            "Prune old canes annually to stimulate vigorous new growth",
        ],
        "severity": "none",
    },
    "Cherry_(including_sour)___Powdery_mildew": {
        "description": "Powdery mildew of cherry is caused by Podosphaera clandestina. It appears as a white, powdery coating on young leaves, shoots, and fruit, causing leaf curling and premature drop.",
        "causes": [
            "Fungal pathogen Podosphaera clandestina",
            "Warm days (20–27°C) with cool nights and high relative humidity",
            "Shaded, crowded canopy conditions",
            "Overwintering mycelium in infected buds",
        ],
        "treatment": [
            "Apply sulfur, potassium bicarbonate, or trifloxystrobin fungicides at first sign",
            "Prune infected shoots immediately to below the mildew margin",
            "Use horticultural oil sprays to smother existing infections",
            "Apply fungicides every 10–14 days during high-risk periods",
        ],
        "prevention": [
            "Prune trees to open canopy and reduce humidity",
            "Avoid excessive nitrogen fertilization that promotes succulent growth",
            "Plant in well-ventilated locations with full sun exposure",
            "Select resistant cherry varieties when possible",
        ],
        "severity": "moderate",
    },
    "Cherry_(including_sour)___healthy": {
        "description": "The cherry plant is healthy with no visible disease symptoms.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Monitor regularly for brown rot, bacterial canker, and leaf spot",
            "Maintain adequate boron and calcium levels in soil",
            "Avoid overhead irrigation to reduce foliar disease risk",
            "Net trees to protect fruit from birds",
        ],
        "severity": "none",
    },
    "Corn_(maize)___Cercospora_leaf_spot_Gray_leaf_spot": {
        "description": "Gray leaf spot (GLS) is caused by Cercospora zeae-maydis and is one of the most prevalent and damaging corn diseases globally. It produces rectangular, gray-to-brown lesions parallel to leaf veins.",
        "causes": [
            "Fungal pathogen Cercospora zeae-maydis",
            "Warm temperatures (25–30°C) with extended leaf wetness periods",
            "High humidity and foggy conditions",
            "Reduced-tillage systems leaving infected crop residue",
        ],
        "treatment": [
            "Apply strobilurin or triazole fungicides (azoxystrobin, propiconazole) at VT/R1 stage",
            "Scout fields regularly and apply fungicides when conditions favor disease spread",
            "Improve field drainage to reduce humidity within canopy",
        ],
        "prevention": [
            "Plant resistant hybrids with high GLS tolerance ratings",
            "Rotate crops — avoid planting corn after corn",
            "Till residue to accelerate decomposition and reduce inoculum",
            "Optimize plant density and row spacing to improve airflow",
        ],
        "severity": "high",
    },
    "Corn_(maize)___Common_rust_": {
        "description": "Common rust is caused by Puccinia sorghi. It is characterized by small, cinnamon-brown pustules scattered on both leaf surfaces, potentially causing significant yield loss in susceptible hybrids.",
        "causes": [
            "Fungal pathogen Puccinia sorghi",
            "Cool temperatures (16–23°C) and high relative humidity",
            "Wind-dispersed urediniospores from southern states or tropical regions",
            "Susceptible hybrid genetics",
        ],
        "treatment": [
            "Apply fungicides (trifloxystrobin, pyraclostrobin) when rust is first detected before VT stage",
            "Focus fungicide application on upper canopy leaves",
            "Monitor fields weekly once tasseling begins",
        ],
        "prevention": [
            "Plant rust-resistant hybrids — the most effective control measure",
            "Avoid late planting which increases exposure risk in cool fall conditions",
            "Scout fields from V6 onwards in high-risk regions",
        ],
        "severity": "moderate",
    },
    "Corn_(maize)___Northern_Leaf_Blight": {
        "description": "Northern leaf blight (NLB) is caused by Exserohilum turcicum. It produces large, cigar-shaped, gray-green to tan lesions (up to 15 cm) on corn leaves, often causing significant defoliation.",
        "causes": [
            "Fungal pathogen Exserohilum turcicum",
            "Moderate temperatures (18–27°C) with extended leaf wetness",
            "Dense plant canopies with poor airflow",
            "Infected corn residue in fields",
        ],
        "treatment": [
            "Apply strobilurin + triazole fungicide mixtures at VT/R1 if disease present in upper canopy",
            "Prioritize protecting ear leaves and above during grain fill",
        ],
        "prevention": [
            "Plant NLB-resistant hybrids (Ht1, Ht2, HtN resistance genes)",
            "Rotate with non-host crops (soybean, small grains)",
            "Till fields after harvest to break down infected residue",
            "Avoid excessive plant population density",
        ],
        "severity": "high",
    },
    "Corn_(maize)___healthy": {
        "description": "The corn plant is healthy with no visible disease symptoms.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Monitor for pests (corn rootworm, aphids, corn earworm)",
            "Maintain balanced NPK fertility program",
            "Scout for early signs of NLB, GLS, and common rust weekly",
            "Ensure adequate soil drainage to prevent root rot",
        ],
        "severity": "none",
    },
    "Grape___Black_rot": {
        "description": "Grape black rot is caused by Guignardia bidwellii and is one of the most destructive grape diseases. It causes brown leaf spots and, critically, causes berries to shrivel into hard, black, mummified structures.",
        "causes": [
            "Fungal pathogen Guignardia bidwellii",
            "Warm, wet conditions (21–29°C) during spring bloom and fruit set",
            "Mummified berries and infected canes as overwintering inoculum",
            "Prolonged leaf wetness and rainfall events",
        ],
        "treatment": [
            "Apply fungicides (myclobutanil, captan, or mancozeb) from early shoot growth through veraison",
            "Remove and destroy all mummified berries and infected canes",
            "Apply protectant sprays 7–10 days apart or more frequently during wet periods",
        ],
        "prevention": [
            "Remove mummified berries from vines and soil before dormancy ends",
            "Maintain open vine canopy through aggressive shoot positioning and leaf removal",
            "Select disease-tolerant varieties for high-pressure regions",
            "Ensure good air movement through vineyard with appropriate row orientation",
        ],
        "severity": "high",
    },
    "Grape___Esca_(Black_Measles)": {
        "description": "Esca (black measles) is a complex grapevine trunk disease caused by a consortium of wood-infecting fungi. It causes interveinal leaf scorching, berry spotting, and in severe cases, sudden vine collapse.",
        "causes": [
            "Fungal complex including Phaeomoniella chlamydospora and Phaeoacremonium minimum",
            "Infection through pruning wounds, especially in wet weather",
            "Stress factors including drought, excessive vigor, or freeze injury",
            "Long-term accumulation of fungal toxins in wood tissue",
        ],
        "treatment": [
            "There is no curative treatment — focus on management and prevention",
            "Remove and destroy severely affected vines",
            "Implement foliar nutrition programs to support vine health",
            "In some regions, trunk renewal (retraining) can extend vine life",
        ],
        "prevention": [
            "Prune vines during dry weather to minimize wound exposure time",
            "Apply wound sealants containing fungicide immediately after pruning",
            "Avoid large pruning wounds — use double pruning system",
            "Remove and burn infected wood",
        ],
        "severity": "high",
    },
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {
        "description": "Grape leaf blight caused by Pseudocercospora vitis produces dark brown to reddish-brown angular spots on leaves, often bordered by leaf veins. Heavy infections cause premature defoliation.",
        "causes": [
            "Fungal pathogen Pseudocercospora vitis",
            "Warm, humid conditions during summer",
            "Dense canopy with poor air circulation",
            "Extended periods of leaf wetness",
        ],
        "treatment": [
            "Apply copper-based or strobilurin fungicides at first sign of symptoms",
            "Improve canopy openness through shoot thinning and leaf removal",
            "Maintain fungicide spray schedule through summer months",
        ],
        "prevention": [
            "Train vines to maximize canopy airflow and light penetration",
            "Avoid excessive nitrogen fertilization",
            "Monitor vines regularly from mid-summer onward",
            "Remove infected leaves promptly to limit spore spread",
        ],
        "severity": "moderate",
    },
    "Grape___healthy": {
        "description": "The grapevine is healthy with no visible disease symptoms.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Maintain a structured spray program for powdery and downy mildew prevention",
            "Monitor for mealybugs, leafhoppers, and bunch moths",
            "Ensure optimal pruning strategy for variety and training system",
            "Test soil and petioles annually for nutrient status",
        ],
        "severity": "none",
    },
    "Orange___Haunglongbing_(Citrus_greening)": {
        "description": "Huanglongbing (HLB), or citrus greening, is arguably the most destructive citrus disease worldwide. It is caused by the bacterium Candidatus Liberibacter asiaticus and has devastated citrus industries globally. There is currently no cure.",
        "causes": [
            "Bacterial pathogen Candidatus Liberibacter asiaticus",
            "Transmitted by the Asian citrus psyllid (Diaphorina citri)",
            "Infected planting material",
            "Movement of infested plant material across regions",
        ],
        "treatment": [
            "No curative treatment currently exists for HLB",
            "Intensive nutritional management (micronutrients, foliar sprays) to extend productive life",
            "Antibiotics (oxytetracycline) may slow progression — check local regulations",
            "Remove and destroy severely infected trees to limit psyllid population",
        ],
        "prevention": [
            "Use certified HLB-free planting material only",
            "Implement intensive psyllid monitoring and control programs with insecticides",
            "Establish physical barriers (screening) in nurseries and young orchards",
            "Report suspected cases immediately to agricultural authorities",
        ],
        "severity": "critical",
    },
    "Peach___Bacterial_spot": {
        "description": "Bacterial spot of peach is caused by Xanthomonas arboricola pv. pruni. It causes water-soaked lesions on leaves that turn angular and dark, fruit spots, and defoliation under severe conditions.",
        "causes": [
            "Bacterial pathogen Xanthomonas arboricola pv. pruni",
            "Warm, rainy conditions with wind-driven rain during bloom and early fruit development",
            "Wounds from sand blasting, insects, or hail",
            "Overhead irrigation promoting bacterial splash dispersal",
        ],
        "treatment": [
            "Apply copper hydroxide or copper sulfate sprays starting at bud swell",
            "Use oxytetracycline (where approved) during bloom in high-pressure situations",
            "Maintain copper spray program at 10–14 day intervals through early fruit development",
            "Remove and destroy heavily infected shoots during dormant pruning",
        ],
        "prevention": [
            "Plant in wind-protected locations or establish windbreaks",
            "Select resistant peach and nectarine varieties",
            "Avoid overhead irrigation — use drip or micro-sprinkler systems",
            "Apply dormant copper sprays to reduce inoculum levels",
        ],
        "severity": "high",
    },
    "Peach___healthy": {
        "description": "The peach tree is healthy with no visible disease symptoms.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Monitor for peach leaf curl in early spring",
            "Maintain brown rot fungicide program during bloom and pre-harvest",
            "Thin fruit to 15–20 cm spacing for optimal size and to reduce disease pressure",
            "Prune annually to maintain open, well-aerated canopy structure",
        ],
        "severity": "none",
    },
    "Pepper,_bell___Bacterial_spot": {
        "description": "Bacterial spot of pepper is caused by Xanthomonas euvesicatoria and related species. It produces small, water-soaked lesions on leaves, stems, and fruit, leading to defoliation and significant fruit loss.",
        "causes": [
            "Bacterial pathogen Xanthomonas euvesicatoria",
            "Warm, wet weather with frequent rain (24–30°C)",
            "Contaminated seed or transplants",
            "Wind and rain dispersal of bacteria",
        ],
        "treatment": [
            "Apply copper bactericides combined with mancozeb at 5–7 day intervals",
            "Remove and destroy heavily infected plant material",
            "Avoid working in fields when foliage is wet",
        ],
        "prevention": [
            "Use certified disease-free seed and hot water seed treatment (52°C for 30 minutes)",
            "Plant resistant pepper varieties",
            "Rotate peppers with non-solanaceous crops for minimum 3 years",
            "Use drip irrigation and avoid overhead watering",
        ],
        "severity": "moderate",
    },
    "Pepper,_bell___healthy": {
        "description": "The bell pepper plant is healthy with no visible disease symptoms.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Monitor for aphids and thrips which can transmit viral diseases",
            "Maintain consistent soil moisture to prevent blossom end rot",
            "Scout for early signs of phytophthora blight, especially after heavy rain",
            "Practice 3-year crop rotation with non-solanaceous crops",
        ],
        "severity": "none",
    },
    "Potato___Early_blight": {
        "description": "Early blight of potato is caused by Alternaria solani. It produces dark brown, concentric ring target-like lesions on older leaves, moving progressively up the plant, reducing photosynthesis and yield.",
        "causes": [
            "Fungal pathogen Alternaria solani",
            "Warm temperatures (24–29°C) with alternating wet and dry periods",
            "Plant stress from nutrient deficiency, drought, or excessive crop load",
            "Infected volunteer potatoes and crop debris",
        ],
        "treatment": [
            "Apply fungicides (azoxystrobin, chlorothalonil, mancozeb) at 7–10 day intervals",
            "Begin spraying before disease appears when conditions are favorable",
            "Remove and destroy infected lower leaves",
            "Ensure adequate potassium and calcium nutrition to improve plant resistance",
        ],
        "prevention": [
            "Use certified seed potatoes and plant in well-drained soils",
            "Avoid stressing plants through adequate irrigation and fertility management",
            "Rotate crops — avoid planting potatoes or tomatoes in same field for 2–3 years",
            "Select varieties with moderate early blight tolerance",
        ],
        "severity": "moderate",
    },
    "Potato___Late_blight": {
        "description": "Late blight, caused by Phytophthora infestans, is the most devastating potato disease in history — responsible for the Irish potato famine. It spreads with frightening speed under cool, wet conditions, destroying entire fields within days.",
        "causes": [
            "Oomycete pathogen Phytophthora infestans",
            "Cool temperatures (10–24°C) with extended leaf wetness (>12 hours)",
            "Infected seed tubers carrying the pathogen",
            "Wind-dispersed sporangia from neighboring infected fields",
        ],
        "treatment": [
            "Apply fungicides immediately at first sign of disease (metalaxyl, cymoxanil, chlorothalonil)",
            "Use alternating chemistry to prevent resistance development",
            "Remove and destroy infected haulm before harvest",
            "Delay harvest until 2–3 weeks after haulm destruction to allow skin set",
        ],
        "prevention": [
            "Use certified disease-free seed tubers",
            "Plant resistant varieties where available",
            "Monitor Blight forecasting services (e.g., BlightCast) and spray prophylactically",
            "Ensure good field drainage and avoid overhead irrigation",
        ],
        "severity": "critical",
    },
    "Potato___healthy": {
        "description": "The potato plant is healthy with no visible disease symptoms.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Implement a preventive late blight spray program from canopy closure",
            "Monitor for Colorado potato beetle and aphid infestations",
            "Maintain hilling to prevent tuber greening and minimize late blight tuber infection",
            "Source certified seed potatoes from reputable suppliers",
        ],
        "severity": "none",
    },
    "Raspberry___healthy": {
        "description": "The raspberry plant is healthy with no visible disease symptoms.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Monitor for cane botrytis and cane blight annually",
            "Remove old floricanes after harvest to reduce disease pressure",
            "Ensure adequate soil drainage — raspberries are highly susceptible to root rot",
            "Maintain proper plant spacing to maximize air circulation",
        ],
        "severity": "none",
    },
    "Soybean___healthy": {
        "description": "The soybean plant is healthy with no visible disease symptoms.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Scout for sudden death syndrome, soybean cyst nematode, and frogeye leaf spot",
            "Rotate with non-host crops to manage SCN populations",
            "Avoid compacted soils and optimize drainage",
            "Choose varieties with package resistance to regional threats",
        ],
        "severity": "none",
    },
    "Squash___Powdery_mildew": {
        "description": "Powdery mildew of squash is caused primarily by Podosphaera xanthii. It produces characteristic white, powdery fungal growth on leaf surfaces, reducing photosynthesis and shortening the productive season.",
        "causes": [
            "Fungal pathogen Podosphaera xanthii",
            "Warm, dry days (20–27°C) with high relative humidity at night",
            "Dense plantings with poor air circulation",
            "Airborne conidia — does not require leaf wetness for infection",
        ],
        "treatment": [
            "Apply potassium bicarbonate, sulfur, or trifloxystrobin fungicides at first sign",
            "Use horticultural oils or neem oil as organic alternatives",
            "Remove and dispose of severely infected leaves",
            "Apply fungicides every 7–14 days throughout the season",
        ],
        "prevention": [
            "Space plants widely to maximize air movement",
            "Avoid excessive nitrogen fertilization which promotes succulent growth",
            "Plant resistant squash and zucchini varieties",
            "Avoid overhead irrigation in the evening",
        ],
        "severity": "moderate",
    },
    "Strawberry___Leaf_scorch": {
        "description": "Strawberry leaf scorch is caused by the fungus Diplocarpon earlianum (anamorph: Marssonina fragariae). It creates small, dark purple spots on leaves that expand and coalesce, giving leaves a scorched appearance.",
        "causes": [
            "Fungal pathogen Diplocarpon earlianum",
            "Wet spring weather promoting spore dispersal",
            "Overhead irrigation",
            "Dense plantings with poor air circulation",
        ],
        "treatment": [
            "Apply fungicides (captan, thiram, or myclobutanil) starting early season",
            "Remove and destroy infected leaves and old foliage after harvest",
            "Renovate plantings by mowing and thinning after last harvest",
        ],
        "prevention": [
            "Establish new plantings with certified disease-free transplants",
            "Maintain adequate plant spacing and row width",
            "Use drip irrigation instead of overhead watering",
            "Select tolerant varieties (Albion, Seascape, Chandler)",
        ],
        "severity": "moderate",
    },
    "Strawberry___healthy": {
        "description": "The strawberry plant is healthy with no visible disease symptoms.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Monitor for two-spotted spider mites and strawberry bud weevil",
            "Maintain renovation program after harvest to rejuvenate planting",
            "Test soil annually — maintain pH 5.8–6.2 for optimal nutrition",
            "Scout for grey mould (Botrytis) during flowering and fruit ripening",
        ],
        "severity": "none",
    },
    "Tomato___Bacterial_spot": {
        "description": "Bacterial spot of tomato is caused by Xanthomonas species and produces water-soaked lesions on leaves, stems, and fruit. Infected fruit develop raised, scab-like spots reducing marketability.",
        "causes": [
            "Xanthomonas euvesicatoria, X. vesicatoria, X. perforans and X. gardneri",
            "Warm, wet conditions (24–30°C) with rain and wind",
            "Contaminated seed or infected transplants",
            "Mechanical spread during wet field operations",
        ],
        "treatment": [
            "Apply copper + mancozeb sprays on 5–7 day schedule",
            "Use bacteriophage-based biocontrol products (OmniLytics) as supplement",
            "Remove and dispose of heavily infected plants",
            "Avoid overhead irrigation and reduce field operations during wet conditions",
        ],
        "prevention": [
            "Start with pathogen-free seed — use hot water seed treatment (52°C / 30 min)",
            "Rotate tomatoes with non-solanaceous crops for 2–3 years",
            "Plant resistant varieties where available",
            "Use drip irrigation and stake plants to improve air circulation",
        ],
        "severity": "moderate",
    },
    "Tomato___Early_blight": {
        "description": "Early blight of tomato caused by Alternaria solani produces distinctive concentric-ring target lesions, primarily on older, stressed leaves. It progresses upward through the canopy under warm, alternating wet-dry conditions.",
        "causes": [
            "Fungal pathogen Alternaria solani",
            "Warm temperatures (24–29°C) with alternating wet and dry periods",
            "Plant stress from nutrient deficiency or heavy crop load",
            "Soil splash dispersing spores to lower leaves",
        ],
        "treatment": [
            "Apply fungicides (azoxystrobin, chlorothalonil, copper) at 7–10 day intervals",
            "Apply mulch to prevent soil splash dispersal",
            "Remove infected lower leaves immediately upon detection",
            "Ensure adequate phosphorus, potassium, and calcium nutrition",
        ],
        "prevention": [
            "Use certified, disease-free seed and resistant varieties",
            "Apply organic mulch (straw) to prevent soil splash",
            "Space plants adequately and stake or cage for airflow",
            "Implement 3-year crop rotation",
        ],
        "severity": "moderate",
    },
    "Tomato___Late_blight": {
        "description": "Late blight of tomato caused by Phytophthora infestans can destroy entire fields within days. It produces large, water-soaked, greasy-looking lesions on leaves with a white mold on leaf undersides under humid conditions.",
        "causes": [
            "Oomycete pathogen Phytophthora infestans",
            "Cool, wet weather (10–24°C) with extended leaf wetness",
            "Infected potato fields or volunteer tomato plants as inoculum source",
            "Wind dispersal of sporangia",
        ],
        "treatment": [
            "Apply fungicides immediately at first detection (metalaxyl-M, cymoxanil, fluazinam)",
            "Use multi-site protectant fungicides and rotate to prevent resistance",
            "Remove and destroy infected plants — do not compost",
            "Harvest promptly — inspect tubers/fruit carefully",
        ],
        "prevention": [
            "Monitor late blight forecasting services and spray preventively",
            "Plant resistant tomato varieties",
            "Eliminate volunteer potato and tomato plants nearby",
            "Avoid overhead irrigation — use drip systems",
        ],
        "severity": "critical",
    },
    "Tomato___Leaf_Mold": {
        "description": "Tomato leaf mold is caused by Passalora fulva (formerly Cladosporium fulvum). It primarily affects greenhouse tomatoes, producing olive-green to gray mold on leaf undersides and pale yellow spots on upper surfaces.",
        "causes": [
            "Fungal pathogen Passalora fulva",
            "High relative humidity (>85%) and temperatures of 22–25°C",
            "Poor greenhouse ventilation",
            "Airborne conidia surviving on greenhouse surfaces",
        ],
        "treatment": [
            "Immediately improve greenhouse ventilation to reduce humidity below 85%",
            "Apply fungicides (chlorothalonil, mancozeb, copper) at early symptom stage",
            "Remove and destroy infected leaves",
            "Heat treat greenhouse structures between crops",
        ],
        "prevention": [
            "Maintain relative humidity below 85% through ventilation and heating",
            "Avoid wetting foliage with overhead irrigation",
            "Plant resistant varieties (most modern greenhouse cultivars have Cf resistance genes)",
            "Sanitize greenhouse structures and equipment between seasons",
        ],
        "severity": "moderate",
    },
    "Tomato___Septoria_leaf_spot": {
        "description": "Septoria leaf spot is caused by Septoria lycopersici and is one of the most common and destructive tomato diseases. It creates small, circular spots with dark margins and lighter centers bearing tiny black pycnidia (fruiting bodies).",
        "causes": [
            "Fungal pathogen Septoria lycopersici",
            "Warm, wet, humid weather (20–25°C) with frequent rain",
            "Soil splash dispersing spores to lower leaves",
            "Infected tomato debris in soil",
        ],
        "treatment": [
            "Apply fungicides (chlorothalonil, mancozeb, copper) on 7–10 day schedule",
            "Mulch soil to prevent splash dispersal",
            "Remove infected lower leaves as soon as symptoms appear",
        ],
        "prevention": [
            "Use certified disease-free seed and resistant varieties",
            "Apply organic mulch (straw) to prevent soil-to-leaf splash",
            "Stake and prune tomatoes to maximize air circulation",
            "Rotate crops and remove infected debris at season end",
        ],
        "severity": "moderate",
    },
    "Tomato___Spider_mites_Two-spotted_spider_mite": {
        "description": "Two-spotted spider mites (Tetranychus urticae) are tiny arachnid pests that cause stippling, bronzing, and eventual collapse of tomato leaves. Heavy infestations produce visible webbing and cause rapid defoliation.",
        "causes": [
            "Arachnid pest Tetranychus urticae",
            "Hot, dry weather (above 28°C) with low humidity",
            "Dusty conditions that kill natural predators",
            "Broad-spectrum insecticide applications eliminating biological controls",
        ],
        "treatment": [
            "Apply acaricides (abamectin, bifenazate, spiromesifen) — rotate modes of action",
            "Use miticides specifically — most insecticides do not control mites",
            "Apply horticultural oil or insecticidal soap to smother mites",
            "Release predatory mites (Phytoseiulus persimilis) for biological control",
        ],
        "prevention": [
            "Avoid broad-spectrum insecticides that kill natural predator populations",
            "Maintain adequate soil moisture — drought-stressed plants are more vulnerable",
            "Monitor undersides of leaves weekly for mite colonies",
            "Establish banker plant systems for predatory mite populations in greenhouses",
        ],
        "severity": "moderate",
    },
    "Tomato___Target_Spot": {
        "description": "Target spot of tomato is caused by Corynespora cassiicola. It produces dark, concentric-ring lesions on leaves, stems, and fruit resembling a bullseye. Severe infections cause premature defoliation and fruit loss.",
        "causes": [
            "Fungal pathogen Corynespora cassiicola",
            "Warm, humid conditions (25–32°C) with high relative humidity",
            "Dense plant canopy restricting airflow",
            "Extended leaf wetness periods",
        ],
        "treatment": [
            "Apply fungicides (chlorothalonil, azoxystrobin, fluxapyroxad) at first symptom",
            "Maintain spray program at 7–10 day intervals during wet weather",
            "Remove infected plant material from field",
        ],
        "prevention": [
            "Train tomato plants to open structure with adequate staking and pruning",
            "Optimize plant spacing to maximize airflow",
            "Use drip irrigation to minimize leaf wetness duration",
            "Select tolerant varieties where available",
        ],
        "severity": "moderate",
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "description": "Tomato Yellow Leaf Curl Virus (TYLCV) is a devastating viral disease transmitted by the silverleaf whitefly (Bemisia tabaci). It causes severe leaf curling, yellowing, stunting, and near-total yield loss in severely infected plants.",
        "causes": [
            "Begomovirus — Tomato Yellow Leaf Curl Virus",
            "Transmitted persistently by silverleaf whitefly Bemisia tabaci",
            "Infected transplants introducing virus into new areas",
            "Weed reservoirs maintaining whitefly and virus populations",
        ],
        "treatment": [
            "There is no curative treatment for TYLCV infection",
            "Manage whitefly populations aggressively with systemic insecticides (imidacloprid, thiamethoxam)",
            "Remove and destroy infected plants to reduce virus source",
            "Apply reflective silver mulch to repel whiteflies",
        ],
        "prevention": [
            "Plant TYLCV-resistant tomato varieties — the most effective management strategy",
            "Use insect-proof netting in seedling production",
            "Establish whitefly monitoring and spray programs from transplanting",
            "Remove weed hosts around field borders",
        ],
        "severity": "critical",
    },
    "Tomato___Tomato_mosaic_virus": {
        "description": "Tomato mosaic virus (ToMV) causes mosaic patterns of light and dark green on leaves, leaf distortion, stunting, and reduced fruit quality. It is mechanically transmitted and extremely stable in the environment.",
        "causes": [
            "Tobamovirus — Tomato mosaic virus",
            "Mechanical transmission via contaminated hands, tools, and clothing",
            "Infected seed or transplants",
            "Virus persisting in root debris and soil for years",
        ],
        "treatment": [
            "There is no cure for ToMV infection",
            "Remove and destroy infected plants to limit spread",
            "Disinfect tools with 10% bleach solution or 70% alcohol between plants",
            "Wash hands thoroughly with soap before entering crop",
        ],
        "prevention": [
            "Plant certified virus-free or virus-indexed seed",
            "Use ToMV-resistant varieties (Tm-2 resistance gene)",
            "Disinfect all tools, equipment, and greenhouse structures",
            "Control aphid and thrip vectors to prevent co-infection with other viruses",
        ],
        "severity": "high",
    },
    "Tomato___healthy": {
        "description": "The tomato plant is healthy with no visible disease symptoms.",
        "causes": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Implement a preventive spray program for early and late blight",
            "Monitor for whiteflies, aphids, and spider mites weekly",
            "Maintain consistent moisture through drip irrigation to prevent blossom end rot",
            "Practice 3-year crop rotation with non-solanaceous crops",
        ],
        "severity": "none",
    },
}


SEVERITY_COLORS = {
    "none": "#22c55e",
    "moderate": "#f59e0b",
    "high": "#ef4444",
    "critical": "#7c3aed",
}


def get_recommendation(raw_class: str) -> dict:
    rec = RECOMMENDATIONS.get(raw_class)
    if rec is None:
        return {
            "description": "No specific recommendation available for this class.",
            "causes": [],
            "treatment": ["Consult a local agronomist for guidance."],
            "prevention": ["Monitor the plant regularly."],
            "severity": "unknown",
            "severity_color": "#6b7280",
        }
    return {**rec, "severity_color": SEVERITY_COLORS.get(rec["severity"], "#6b7280")}